name: Deploy Lambda Function

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r DiscordBot/requirements.txt

    - name: Create deployment package
      run: |
        mkdir deployment
        cp -r DiscordBot/deploy deployment/
        cp -r DiscordBot/lambda deployment/
        cd deployment
        pip install -r requirements.txt --target ./package
        cp -r . ./package
        cd package
        zip -r ../discord-bot-lambda.zip .
        cd ..
      
    - name: Deploy Lambda function
      uses: einaregilsson/lambda-action@v1
      with:
        function_name: discord-bot-lambda
        zip_file: discord-bot-lambda.zip
        region: us-east-2
        environment_variables: |
          DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }}
          GH_TOKEN=${{ secrets.GH_TOKEN }}
          GH_REPO=${{ secrets.GH_REPO }}
          GH_BRANCH=${{ secrets.GH_BRANCH }}
          TFVARS_FOLDER=${{ secrets.TFVARS_FOLDER }}
