name: Deploy Lambda Function

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies into deployment folder
      run: |
        mkdir deployment
        pip install -r DiscordBot/requirements.txt --target deployment/
        cp DiscordBot/*.py deployment/
        cd deployment
        zip -r ../discord-bot-lambda.zip .
        cd ..

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code \
          --function-name discordBot \
          --zip-file fileb://discord-bot-lambda.zip

    - name: Update Lambda environment variables
      run: |
        aws lambda update-function-configuration \
          --function-name discord-bot-lambda \
          --environment "Variables={
            DISCORD_PUBLIC_KEY='${{ secrets.DISCORD_PUBLIC_KEY }}',
            GH_TOKEN='${{ secrets.GH_TOKEN }}',
            GH_REPO='${{ secrets.GH_REPO }}',
            GH_BRANCH='${{ secrets.GH_BRANCH }}',
            TFVARS_FOLDER='${{ secrets.TFVARS_FOLDER }}'
          }"
