name: Run Discord Bot

on:
  workflow_dispatch:  # Manual trigger

jobs:
  discord-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r DiscordBot/requirements.txt

      - name: Run Discord bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
          GITHUB_BRANCH: ${{ secrets.GITHUB_BRANCH }}
          TFVARS_FOLDER: ${{ secrets.TFVARS_FOLDER }}
        run: |
          python DiscordBot/discordbot.py  # Path to your discord bot script inside DiscordBot folder
